### PR TITLE
Dynamics array fix

### LINKED ISSUE #130: Allow multiple Dynamics values per DirectionType
The `DirectionType.dynamics` case currently holds onto a single `Dynamics` as its associated value.

In the MusicXML spec, however, there should be able to be a sequence of `Dynamics` values. In #126, we were able to decode a single `Dynamics` value, which seems to be the vastly more common case.

@DJBen, @bwetherfield, let me know if you've got thoughts on how to deal with this.

### PR DESCRIPTION
**Pull request by bwetherfield**
Fixes #130

### CODE REVIEW

**Comment by jsbean** [comment]
🙌

File: Tests/MusicXMLTests/LilyPondTests/ArticulationsTextsTests.swift [hunk 1]
```diff
@@ -25,13 +25,13 @@ class ArticulationsTextsTests: XCTestCase {
         let expected = Direction(
             [
                 .words(
-                    FormattedText("Normal, Small, Colored, Below",
-                        printStyle: PrintStyle(
-                            position: Position(defaultX: 1, defaultY: -15),
-                            font: Font(size: FontSize(.small)),
-                            color: Color(hexString: "#FF8000")
+                    [FormattedText("Normal, Small, Colored, Below",
```
Comment (jsbean) [inline Tests/MusicXMLTests/LilyPondTests/ArticulationsTextsTests.swift]: I think the indentation got a bit weird here. How about something like this:

```Swift
[
    FormattedText("Normal, Small, Colored, Below",
        printStyle: PrintStyle(
            position: Position(defaultX: 1, defaultY: -15),
            font: Font(size: FontSize(.small)),
            color: Color(hexString: "#FF8000")
        )
    )
]
```

**Comment by jsbean** [comment]
This is great, thanks! Just that one indentation thing and good to go in.
